### ISSUE TITLE
Host selector regression in 3.4.5 (since 3.4.0): :host(:not(.foo))

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#2464]
The following works in 3.4.0 but not in 3.4.5:
```scss
:host(:not(.foo)) {
  left: 0;
}
```

(3.4.5 outputs `{left:0}` here!)

**Comment by mgreter** [comment]
This is already fixed on [latest master][1]. It also seems that sass 3.5 does not support this (beside 3.4 and 4.0 looking ok, only checked via sassmeister)

[1]: http://libsass.ocbnet.ch/srcmap/#Omhvc3QoOm5vdCguZm9vKSkgewogIGxlZnQ6IDA7Cn0=

**Comment by ochafik** [comment]
Just to clarify:
- Still broken in branch `master` ; I've bisected the regression to the hotfix https://github.com/sass/libsass/commit/2d640a738ef04e15239cc1d9965a6ee1ab499bd2
- Broken in branch `3.4-stable`
- Works in branch `3.4.x`

**Comment by ochafik** [comment]
Could this bug please be reopened until master branch is fixed?

**Comment by mgreter** [comment]
Thanks for checking, can confirm this regressed once more. Unfortunately we probably will not be able to fix it without regressing other more common use cases in a forseeable future. See https://github.com/sass/libsass/issues/2055. As said in my initial comment, this does not seem to be supported by original ruby sass 3.5, although it seems to be in 3.4 and 4.0 (as checked via sassmeister).
